#!/usr/bin/env bash
set -euo pipefail

echo "==> Installing dotfiles…"

# Directory where this script lives (your dotfiles repo root)

DOTFILES_DIR="$(
cd "$(dirname "${BASH_SOURCE[0]}")"
pwd
)"

backup() {
local target="$1"
if [ -e "$target" ] && [ ! -L "$target" ]; then
local backup_name="${target}.bak-$(date +%Y%m%d%H%M%S)"
echo "  - Backing up $target -> $backup_name"
mv "$target" "$backup_name"
fi
}

link() {
local src="$1"
local dest="$2"

mkdir -p "$(dirname "$dest")"

if [ -L "$dest" ] && [ "$(readlink "$dest")" = "$src" ]; then
echo "  = Link already correct: $dest"
return
fi

backup "$dest"
ln -sfn "$src" "$dest"
echo "  + Linked $dest -> $src"
}

echo "-> Linking tmux config"
link "$DOTFILES_DIR/tmux.conf" "$HOME/.tmux.conf"

echo "-> Linking git config"
link "$DOTFILES_DIR/gitconfig" "$HOME/.gitconfig"

echo "-> Linking shell shared config"
if [ -f "$HOME/.bashrc" ] || [[ "$SHELL" == *"bash"* ]]; then
  link "$DOTFILES_DIR/bashrc_common" "$HOME/.bashrc_common"
fi
link "$DOTFILES_DIR/zshrc_common" "$HOME/.zshrc_common"

echo "-> Linking Julia startup"
link "$DOTFILES_DIR/julia/startup.jl" "$HOME/.julia/config/startup.jl"

# Create minimal .bashrc if missing, that sources common + local

if [ ! -f "$HOME/.bashrc" ]; then
echo "-> Creating minimal ~/.bashrc"
cat >"$HOME/.bashrc" <<'EOF'

# ~/.bashrc (generated by dotfiles install.sh)

[ -f "$HOME/.bashrc_common" ] && . "$HOME/.bashrc_common"
[ -f "$HOME/.bashrc.local" ] && . "$HOME/.bashrc.local"
EOF
else
echo "  = ~/.bashrc already exists (not touching it)"
fi

# Create minimal .zshrc if missing, that sources common + local

if [ ! -f "$HOME/.zshrc" ]; then
echo "-> Creating minimal ~/.zshrc"
cat >"$HOME/.zshrc" <<'EOF'

# ~/.zshrc (generated by dotfiles install.sh)

[ -f "$HOME/.zshrc_common" ] && . "$HOME/.zshrc_common"
[ -f "$HOME/.zshrc.local" ] && . "$HOME/.zshrc.local"
EOF
else
  if ! grep -q "zshrc_common" "$HOME/.zshrc"; then
    echo "-> Appending sourcing to ~/.zshrc"
    cat >>"$HOME/.zshrc" <<'EOF'

# Added by dotfiles install.sh
[ -f "$HOME/.zshrc_common" ] && . "$HOME/.zshrc_common"
[ -f "$HOME/.zshrc.local" ] && . "$HOME/.zshrc.local"
EOF
  else
    echo "  = ~/.zshrc already sources common config"
  fi
fi

echo "==> Done."

echo
echo "Next steps:"
echo "  - Open a new shell, or run:  source ~/.bashrc  (or ~/.zshrc)"
echo "  - Customize per-machine settings in:"
echo "        ~/.bashrc.local"
echo "        ~/.zshrc.local"
echo "        ~/.julia/config/startup_local.jl"
